# src/main/resources/application.yml
kakao:
  pay:
    host: https://kapi.kakao.com
    admin-key: e13c9e33608549206057a7fdee430ab2 # 실제 발급받은 관리자 키
    cid: TC0ONETIME          # 가맹점 코드 (테스트용), 코드작성 X
    ready-path: /payment/ready  #카카오페이 호출 주소, 코드작성 X
    approve-path: /payment/approve  #카카오페이 인증 주소, 코드작성 X